i = str(input('Digite algo: '))
print('{}O tipo primitivo desse valor é {}{}'.format('\033[37m', type(i), '\033[m'))
print('{}Só tem espaços? {}{}'.format('\033[36m', i.isspace(), '\033[m'))
print('{}É um número? {}{}'.format('\033[35m', i.isnumeric(), '\033[m'))
print('{}É alfabético? {}{}'.format('\033[34m', i.isalpha(), '\033[m'))
print('{}É alfanumérico? {}{}'.format('\033[33m', i.isalnum(), '\033[m'))
print('{}Está em maiúsculas? {}{}'.format('\033[32m', i.isupper(), '\033[n'))
print('{}Está em minúsculas? {}{}'.format('\033[31m', i.islower(), '\033[m'))
print('{}Está capitalizado? {}{}'.format('\033[30m', i.istitle(), '\033[m'))