i = int(input('Digite um número para saber sua tabuada: '))
a = i*1
b = i*2
c = i*3
d = i*4
e = i*5
f = i*6
g = i*7
h = i*8
j = i*9
k = i*10
print('='*15)
print('{} X {:2} = {}'.format(i, 1, a))
print('{} X {:2} = {}'.format(i, 2, b))
print('{} X {:2} = {}'.format(i, 3, c))
print('{} X {:2} = {}'.format(i, 4, d))
print('{} X {:2} = {}'.format(i, 5, e))
print('{} X {:2} = {}'.format(i, 6, f))
print('{} X {:2} = {}'.format(i, 7, g))
print('{} X {:2} = {}'.format(i, 8, h))
print('{} X {:2} = {}'.format(i, 9, j))
print('{} X {:2} = {}'.format(i, 10, k))
print('='*15)