i = str(input('Digite seu nome completo: ')).strip()
m = i.upper()
mm = i.lower()
c = len(i) - i.count(' ')
zika = i.capitalize()
zika2 = zika.split()
zika3 = len(zika2[0])
print('Seu nome em maiúsculas é {}'.format(m))
print('Seu nome em minúsculas é {}'.format(mm))
print('Seu nome completo tem {} letras'.format(c))
print('Seu primeiro nome é {} e ele tem {} letras'.format(zika2[0], zika3))
